import {
  ArrowLeftRight, Minimize2, Sliders, Sparkles,
  Package, FileImage, FilePlus, FileText,
  FileOutput, Files, QrCode, Code2,
  Crop, RotateCcw, FlipHorizontal, Type,
  Pipette, Droplet, Maximize2, SplitSquareHorizontal,
  FileMinus, FileCog, ListOrdered, Image,
  Shield, Unlock, Hash, Baseline, Settings,
  ScanQrCode, Palette, Volume2, Mic, Fingerprint,
  Key, Binary, FileJson, Link2
} from 'lucide-react'

export const TOOLS = [
  // ── Image Tools ─────────────────────────────────
  {
    category: 'Image Tools',
    items: [
      {
        slug:  'image-converter',
        title: 'Image Converter',
        desc:  'Convert between PNG, JPEG, WebP, GIF and BMP formats instantly',
        icon:  ArrowLeftRight,
        color: '#0ea5e9',
        bg:    'rgba(14, 165, 233, 0.1)',
      },
      {
        slug:  'image-compressor',
        title: 'Image Compressor',
        desc:  'Reduce image file size without visible quality loss',
        icon:  Minimize2,
        color: '#10b981',
        bg:    'rgba(16, 185, 129, 0.1)',
      },
      {
        slug:  'image-editor',
        title: 'Image Editor',
        desc:  'Crop, resize, rotate, apply filters and add watermarks',
        icon:  Sliders,
        color: '#a855f7',
        bg:    'rgba(168, 85, 247, 0.1)',
      },
      {
        slug:  'remove-background',
        title: 'Remove Background',
        desc:  'AI-powered background removal — runs entirely in your browser',
        icon:  Sparkles,
        color: '#ec4899',
        bg:    'rgba(236, 72, 153, 0.1)',
        badge: 'AI',
      },
      {
        slug:  'batch-convert',
        title: 'Batch Convert',
        desc:  'Convert multiple images at once and download as ZIP',
        icon:  Package,
        color: '#f59e0b',
        bg:    'rgba(245, 158, 11, 0.1)',
      },
      {
        slug:  'base64',
        title: 'Image to Base64',
        desc:  'Convert any image to Base64 string and back',
        icon:  Code2,
        color: '#64748b',
        bg:    'rgba(100, 116, 139, 0.1)',
      },
      {
        slug:  'resize-image',
        title: 'Resize Image',
        desc:  'Resize images to exact dimensions or scale proportionally.',
        icon:  Maximize2,
        color: '#3b82f6',
        bg:    'rgba(59, 130, 246, 0.1)',
      },
      {
        slug:  'crop-image',
        title: 'Crop Image',
        desc:  'Trim images to the perfect size or aspect ratio.',
        icon:  Crop,
        color: '#14b8a6',
        bg:    'rgba(20, 184, 166, 0.1)',
      },
      {
        slug:  'rotate-image',
        title: 'Rotate Image',
        desc:  'Rotate images clockwise or counter-clockwise.',
        icon:  RotateCcw,
        color: '#f97316',
        bg:    'rgba(249, 115, 22, 0.1)',
      },
      {
        slug:  'flip-image',
        title: 'Flip Image',
        desc:  'Flip images horizontally or vertically.',
        icon:  FlipHorizontal,
        color: '#6366f1',
        bg:    'rgba(99, 102, 241, 0.1)',
      },
      {
        slug:  'watermark-image',
        title: 'Watermark Image',
        desc:  'Add text watermarks to your images to protect your work.',
        icon:  Type,
        color: '#8b5cf6',
        bg:    'rgba(139, 92, 246, 0.1)',
      },
      {
        slug:  'image-metadata',
        title: 'Image Metadata Viewer',
        desc:  'View image dimensions, file type, and size before editing.',
        icon:  FileText,
        color: '#0284c7',
        bg:    'rgba(2, 132, 199, 0.1)',
      },
      {
        slug:  'color-picker',
        title: 'Image Color Picker',
        desc:  'Pick colors from any image and copy HEX values instantly.',
        icon:  Pipette,
        color: '#d97706',
        bg:    'rgba(217, 119, 6, 0.1)',
      },
      {
        slug:  'image-blur',
        title: 'Image Blur Tool',
        desc:  'Apply blur effects to soften backgrounds or create depth.',
        icon:  Droplet,
        color: '#0ea5e9',
        bg:    'rgba(14, 165, 233, 0.1)',
      },
      {
        slug:  'image-sharpen',
        title: 'Image Sharpen Tool',
        desc:  'Enhance edge contrast for a crisper look.',
        icon:  Sparkles,
        color: '#db2777',
        bg:    'rgba(219, 39, 119, 0.1)',
      },
      {
        slug:  'screenshot',
        title: 'Screenshot to Image Converter',
        desc:  'Paste screenshots or upload captures and save as images.',
        icon:  FileImage,
        color: '#4f46e5',
        bg:    'rgba(79, 70, 229, 0.1)',
      },

    ],
  },
  // ── Non-Image Tools ──────────────────────────────
  {
    category: 'Non-Image Tools',
    items: [
      {
        slug:  'pdf-to-image',
        title: 'PDF to Image',
        desc:  'Convert every PDF page to PNG or JPEG images',
        icon:  FileImage,
        color: '#ef4444',
        bg:    'rgba(239, 68, 68, 0.1)',
      },
      {
        slug:  'image-to-pdf',
        title: 'Image to PDF',
        desc:  'Combine one or more images into a single PDF file',
        icon:  FilePlus,
        color: '#f43f5e',
        bg:    'rgba(244, 63, 94, 0.1)',
      },
      {
        slug:  'pdf-to-word',
        title: 'PDF to Word',
        desc:  'Extract text from PDF and export as .docx document',
        icon:  FileText,
        color: '#3b82f6',
        bg:    'rgba(59, 130, 246, 0.1)',
      },
      {
        slug:  'word-to-pdf',
        title: 'Word to PDF',
        desc:  'Convert .docx or .txt files to a clean PDF document',
        icon:  FileOutput,
        color: '#22c55e',
        bg:    'rgba(34, 197, 94, 0.1)',
      },
      {
        slug:  'merge-pdf',
        title: 'Merge PDF',
        desc:  'Combine multiple PDF files into one single document',
        icon:  Files,
        color: '#f59e0b',
        bg:    'rgba(245, 158, 11, 0.1)',
      },
      {
        slug:  'split-pdf',
        title: 'Split PDF',
        desc:  'Extract pages from your PDF or save each page as a separate PDF.',
        icon:  SplitSquareHorizontal,
        color: '#8b5cf6',
        bg:    'rgba(139, 92, 246, 0.1)',
      },
      {
        slug:  'compress-pdf',
        title: 'Compress PDF',
        desc:  'Reduce file size of your PDF while maintaining optimal quality.',
        icon:  FileMinus,
        color: '#10b981',
        bg:    'rgba(16, 185, 129, 0.1)',
      },
      {
        slug:  'rotate-pdf',
        title: 'Rotate PDF',
        desc:  'Rotate specific PDF pages or all pages simultaneously.',
        icon:  FileCog,
        color: '#06b6d4',
        bg:    'rgba(6, 182, 212, 0.1)',
      },
      {
        slug:  'reorder-pdf',
        title: 'Reorder PDF Pages',
        desc:  'Rearrange or delete pages from your PDF document easily.',
        icon:  ListOrdered,
        color: '#3b82f6',
        bg:    'rgba(59, 130, 246, 0.1)',
      },
      {
        slug:  'extract-images-pdf',
        title: 'Extract Images from PDF',
        desc:  'Extract all images embedded inside a PDF document.',
        icon:  Image,
        color: '#ec4899',
        bg:    'rgba(236, 72, 153, 0.1)',
      },
      {
        slug:  'protect-pdf',
        title: 'Protect PDF (Password)',
        desc:  'Secure your PDF with a password to prevent unauthorized access.',
        icon:  Shield,
        color: '#ef4444',
        bg:    'rgba(239, 68, 68, 0.1)',
      },
      {
        slug:  'unlock-pdf',
        title: 'Unlock PDF',
        desc:  'Remove PDF password security to read and edit freely.',
        icon:  Unlock,
        color: '#22c55e',
        bg:    'rgba(34, 197, 94, 0.1)',
      },
      {
        slug:  'add-page-numbers',
        title: 'Add Page Numbers',
        desc:  'Insert page numbers into PDF documents in your chosen position.',
        icon:  Hash,
        color: '#f97316',
        bg:    'rgba(249, 115, 22, 0.1)',
      },
      {
        slug:  'add-watermark-pdf',
        title: 'Add Watermark to PDF',
        desc:  'Stamp an image or text over your PDF in seconds.',
        icon:  Baseline,
        color: '#6366f1',
        bg:    'rgba(99, 102, 241, 0.1)',
      },
      {
        slug:  'pdf-metadata',
        title: 'PDF Metadata Viewer',
        desc:  'View and analyze hidden properties and metadata in a PDF.',
        icon:  Settings,
        color: '#64748b',
        bg:    'rgba(100, 116, 139, 0.1)',
      },
      {
        slug:  'qr-code',
        title: 'QR Code Overlay',
        desc:  'Generate a QR code and stamp it onto any image',
        icon:  QrCode,
        color: '#14b8a6',
        bg:    'rgba(20, 184, 166, 0.1)',
      },
      {
        slug:  'qr-generator',
        title: 'QR Code Generator',
        desc:  'Create custom QR codes for any text or URL',
        icon:  QrCode,
        color: '#0d9488',
        bg:    'rgba(13, 148, 136, 0.1)',
      },
      {
        slug:  'qr-scanner',
        title: 'QR Code Scanner',
        desc:  'Scan QR codes from images or using your camera',
        icon:  ScanQrCode,
        color: '#0891b2',
        bg:    'rgba(8, 145, 178, 0.1)',
      },
      {
        slug:  'gen-color-picker',
        title: 'Color Picker',
        desc:  'Interactive color palette and HEX/RGB/HSL generator',
        icon:  Palette,
        color: '#4f46e5',
        bg:    'rgba(79, 70, 229, 0.1)',
      },
      {
        slug:  'text-to-speech',
        title: 'Text to Speech',
        desc:  'Convert any text into natural sounding spoken audio',
        icon:  Volume2,
        color: '#7c3aed',
        bg:    'rgba(124, 58, 237, 0.1)',
      },
      {
        slug:  'speech-to-text',
        title: 'Speech to Text',
        desc:  'Transcribe your voice to text in real-time',
        icon:  Mic,
        color: '#c026d3',
        bg:    'rgba(192, 38, 211, 0.1)',
      },
      {
        slug:  'uuid-generator',
        title: 'UUID Generator',
        desc:  'Generate random v4 UUIDs for your development needs',
        icon:  Fingerprint,
        color: '#475569',
        bg:    'rgba(71, 85, 105, 0.1)',
      },
      {
        slug:  'password-generator',
        title: 'Password Generator',
        desc:  'Create strong, secure passwords with custom options',
        icon:  Key,
        color: '#059669',
        bg:    'rgba(5, 150, 105, 0.1)',
      },
      {
        slug:  'base64-text',
        title: 'Base64 Encoder/Decoder',
        desc:  'Easily encode and decode text to Base64 format',
        icon:  Binary,
        color: '#52525b',
        bg:    'rgba(82, 82, 91, 0.1)',
      },
      {
        slug:  'json-formatter',
        title: 'JSON Formatter',
        desc:  'Beautify, minify, and validate your JSON data',
        icon:  FileJson,
        color: '#2563eb',
        bg:    'rgba(37, 99, 235, 0.1)',
      },
      {
        slug:  'url-encoder',
        title: 'URL Encoder/Decoder',
        desc:  'Encode and decode strings for URLs and parameters',
        icon:  Link2,
        color: '#ea580c',
        bg:    'rgba(234, 88, 12, 0.1)',
      },
    ],
  },
]
